### ISSUE TITLE
Fimber.d not work when use in Isolates

### ISSUE THREAD

**Issue by anticafe** [magillus/flutter-fimber#59]
I try to use `Fimber.d()` in an Isolates and notice it doesn't print any log.
Version: `fimber: ^0.3.2`.
As I now, Fimber isn't Dart plugin, so do you know why it doesn't work in Isolates?

**Comment by magillus** [comment]
Thank you for writing about this, I didn't run into it yet - since my usage of Isolates is minimal.

I believe that on each Isolate you need to "plan a tree" That is because they are separate and they do not share memory. That is why your `plantTree` on first (lets call it main) Isolate is not available on second.

Create a common static method that setups logging trees and execute that on start of the new Isolate.

**Comment by magillus** [comment]
@anticafe I hope that answered your question - please reopen and comment if not and provide some more details.
