### ISSUE TITLE
How do you log to a file for Android emulator?

### ISSUE THREAD

**Issue by remoteportal** [magillus/flutter-fimber#66]
And, can that file be easily visible using Windows?

**Comment by magillus** [comment]
Log to file on Android is tricky because of permissions and from windows to access the app's directory is not easy to do without rooted phone. (It was some time since I did it so maybe there is a way to do it)
With new `0.4.0` version of fimber - you need to add `fimber_io` and use files logger with file path that app should have permission to do.
Try first use app's directory then sdcard directory and see if it works.

**Comment by magillus** [comment]
How is going - did I answered your question @remoteportal ?
Let me know if I can help with anything.

**Comment by magillus** [comment]
Closing issue, feel free to reopen if my comment didn't answer your question.
