### ISSUE TITLE
Logs with broken characters 

### ISSUE THREAD

**Issue by luan-silva** [magillus/flutter-fimber#68]
I/flutter (29013): [32m2020-01-30T12:09:16.341436	D	AdsUtils._handleEvent:	 New Banner Ad loaded![0m

You can see them in the beginning and in the end

**Comment by magillus** [comment]
Can you provide which OS you use it on or type of application: CLI/Flutter, etc.
`�[32m` - seems like it is using Colorize in logger, so it can be displayed like this in a file/ console output without support.
Also what tree do you use? `DebugTree` got extra parameter `useColors` but that seems like not enabled in your case since INFO log level does use default, unless you changed colors per each level via `colorizeMap`

**Comment by luan-silva** [comment]
I got confused, yes I was seeing the logs on the run tab not in the logcat from Android Studio (that is perfectly fine) and I was using useColors: true ( I have a custom list of log levels for debug because I wanted all levels in debug and only verbose for release)  BUT the colors didn't change in logcat of Android Studio

**Comment by magillus** [comment]
Some consoles (logs are put into the console) support the colors codes and they show correctly colored them. Some do not do it and you see those codes in logs.
If you plan to use logs to view them in text editor or tool that doesn't support it - disable the `useColors` 
You can have 2 `DebugTree` one per each build (release/debug) with correct settings and also expected log levels.

**Comment by magillus** [comment]
If that is not what you want. Can you describe what you look for with the logging?

**Comment by magillus** [comment]
Closing issue, please feel free to open if you still have this problem
